"""Shared MCP tool metadata."""

TOOL_NAMES = (
    "get_repo_info",
    "git_status",
    "git_log",
    "git_current_commit",
    "list_files",
    "search_code",
    "read_code_file",
    "git_diff",
    "workspace_doctor",
    "list_recent_research_runs",
    "get_latest_universe_run",
    "read_universe_run",
    "summarise_universe_run",
    "list_symbol_reports",
    "read_symbol_report",
    "compare_universe_runs",
    "find_candidate_symbols",
    "find_interesting_symbols",
    "filter_symbol_results",
    "db_list_databases",
    "db_list_tables",
    "db_describe_table",
    "db_preview_table",
    "db_get_symbol_bars",
    "db_get_latest_catalysts",
    "db_get_trade_attribution",
    "db_select",
    "export_diagnostics_zip",
)
