"""Public contracts for Stocker's prospective-record and shadow runtime."""

from stocker_runtime.domain import (
    MAX_MARKET_EVENT_PAYLOAD_BYTES,
    IdeaOutput,
    JsonValue,
    MarketEvent,
    Observation,
    OutputKind,
    ProposedPosition,
    ProposedTrade,
    ProposedTradeLeg,
    ProtectedDataClass,
    RuntimeMode,
    ShadowCostPolicy,
    ShadowFillPolicy,
    Signal,
    canonical_json_bytes,
)
from stocker_runtime.ideas import (
    MAX_EVENTS_PER_BATCH,
    MAX_REHYDRATED_BYTES,
    MAX_REHYDRATED_EVENTS,
    AncestorPageContinuation,
    ContinuationRequest,
    DiscoveryReceipt,
    ExactEventsContinuation,
    IdeaActivation,
    IdeaBatch,
    IdeaEvaluation,
    IdeaManifest,
    IdeaPlugin,
    MarketDataInterest,
    MarketDataRequirement,
)

__all__ = [
    "IdeaOutput",
    "IdeaActivation",
    "AncestorPageContinuation",
    "ContinuationRequest",
    "ExactEventsContinuation",
    "IdeaBatch",
    "IdeaEvaluation",
    "IdeaManifest",
    "IdeaPlugin",
    "DiscoveryReceipt",
    "JsonValue",
    "MAX_EVENTS_PER_BATCH",
    "MAX_REHYDRATED_BYTES",
    "MAX_REHYDRATED_EVENTS",
    "MAX_MARKET_EVENT_PAYLOAD_BYTES",
    "MarketDataRequirement",
    "MarketDataInterest",
    "MarketEvent",
    "Observation",
    "OutputKind",
    "ProtectedDataClass",
    "ProposedPosition",
    "ProposedTrade",
    "ProposedTradeLeg",
    "RuntimeMode",
    "ShadowCostPolicy",
    "ShadowFillPolicy",
    "Signal",
    "canonical_json_bytes",
]
__version__ = "0.1.0"
