PAPER:
  environment: PAPER
  host: 127.0.0.1
  port: 4002
  client_id: 21
  connect_timeout_seconds: 5
  request_timeout_seconds: 60

LIVE:
  environment: LIVE
  host: 127.0.0.1
  port: 4001
  client_id: 22
  connect_timeout_seconds: 5
  request_timeout_seconds: 60
